In [1]:
import requests, bs4
import pandas as pd
from lxml import html
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus, unquote
from bs4 import BeautifulSoup
import json
import xmltodict
import re
import pickle

In [2]:
# 엑세스 토큰발급
url = 'https://sgisapi.kostat.go.kr/OpenAPI3/auth/authentication.json'
params = {
        "consumer_key": "367e41f572b2440d8023",
        "consumer_secret": "d63aed3ea67741e5a424",
}

response = requests.get(url, params=params)
res = response.json()
token = res['result']['accessToken']
token

'd870e0aa-8a02-4195-a3bb-b4f73210791e'

In [3]:
# pkl 파일 로드
with open('temp(dong).pkl', 'rb') as f:
    dong = pickle.load(f)

In [4]:
dong

,addr_name_gu,addr_name_dong,addr_code,x,y,poly_type,polygon,locate_new,locate_old,locate_restaurant,locate_restaurant_total,density
0,강남구,개포1동,1123068,137.083527,28.291943,Polygon,"[(127.058262005097, 37.48473924045432), (127.0...",[2110993],NaN,"[(23499457, 0), (17131741, 0), (20482063, 8), ...","[(127.054375095471, 37.4832728348861, 23499457...",7.428571
1,강남구,개포2동,1123080,137.091733,28.296745,Polygon,"[(127.07276621452564, 37.49190758430041), (127...","[2110994, 2130310]","[1001475, 1000892, 1000928]","[(20484278, 3), (25504231, 0), (15479972, 2), ...","[(127.067636863204, 37.4888476666906, 20484278...",3.928011
2,강남구,개포4동,1123071,137.080225,28.285083,Polygon,"[(127.05175940694477, 37.48479324866259), (127...","[2110981, 2110977, 2110983, 2110984, 2110980, ...","[1000889, 1000890, 1000895, 1000891, 1000903, ...","[(20026781, 0), (23205621, 5), (25841198, 0), ...","[(127.047819226133, 37.4777507521333, 20026781...",3.724813
3,강남구,논현1동,1123052,137.119134,28.261237,Polygon,"[(127.0245113543698, 37.50448575253878), (127....","[2110950, 2110952, 2110953, 2110955, 2120178, ...","[1000896, 1000897, 1000898, 1000938, 1000886, ...","[(20694126, 1), (20024580, 7), (15500579, 0), ...","[(127.021869480819, 37.510850793909, 20694126)...",2.344868
4,강남구,논현2동,1123053,137.123537,28.268627,Polygon,"[(127.03471848932787, 37.507565199603214), (12...","[2110966, 2110970, 2110968, 2110961, 2110957, ...","[1000936, 1000924, 1000926, 1000907, 1000908, ...","[(25363926, 1), (20027263, 0), (20379364, 0), ...","[(127.037621922455, 37.5217387643908, 25363926...",1.556067
...,...,...,...,...,...,...,...,...,...,...,...,...
404,중구,중림동,1102068,137.165886,28.210413,Polygon,"[(126.9700057920628, 37.56197371744504), (126....",[2120018],[1001285],"[(16095832, 0), (20480938, 1), (25330385, 1), ...","[(126.965765624561, 37.5583985853813, 16095832...",4.253463
405,중구,청구동,1102072,137.169434,28.248742,Polygon,"[(127.01623805512705, 37.55934349966869), (127...",[2110054],"[1000043, 1000034]","[(20468954, 0), (20778056, 7), (25787018, 8), ...","[(127.011818363767, 37.5559547298335, 20468954...",5.477680
406,중구,필동,1102057,137.167033,28.232372,Polygon,"[(126.99145018675534, 37.56327940446108), (126...","[2110043, 2110042, 2120032, 2130034]","[1000046, 1001192, 1001199]","[(20660147, 5), (15523914, 2), (15518460, 0), ...","[(127.000684189012, 37.5625287427188, 20660147...",3.466863
407,중구,황학동,1102067,137.182873,28.252484,Polygon,"[(127.02313682540297, 37.57196080915371), (127...","[2110055, 2110057, 2130054, 2130055, 2130052]","[1000028, 1000029, 1001284]","[(16173619, 1), (16518825, 1), (20478568, 2), ...","[(127.02065930378, 37.5688052133752, 16173619)...",4.648250
408,중구,회현동,1102054,137.165798,28.219124,Polygon,"[(126.98156612092468, 37.561130394620264), (12...","[2110040, 2110039, 2120024, 2120043, 2130025, ...","[1000044, 1000048, 1001273]","[(25831772, 1), (20376411, 0), (23591759, 2), ...","[(126.974012327868, 37.559542778357, 25831772)...",3.019942

In [ ]:
# 사업체 증감 수
col_list = []
row_list = []
for i in range(0, len(dong)):
    url = "https://sgisapi.kostat.go.kr/OpenAPI3/startupbiz/corpindecrease.json"
    
    params = {
        "accessToken": "{}".format(token),
        "adm_cd": "{}".format(dong['addr_code'][i])  
    }

    response = requests.get(url, params=params)
    json = response.json()
    if i == 0:
        col_list = list(json['result'][1].keys())
    row_list.append(json['result'][1].values())
df = pd.DataFrame(row_list, columns=col_list)