In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
dong_change = pd.read_csv('../../dataSet/03_행정동별 상권변화지표.csv', encoding='cp949')
dong_change = dong_change[dong_change['기준_년_코드'] == 2021]

In [4]:
dong_change['행정동_코드_명'].value_counts()

신사동      8
송중동      4
삼각산동     4
번1동      4
번2동      4
        ..
시흥5동     4
영등포본동    4
영등포동     4
여의동      4
청운효자동    4
Name: 행정동_코드_명, Length: 423, dtype: int64

In [5]:
# 상권 지표 변경
'''
- LL(다이나믹) : 
    도시재생 및 신규 개발 상권으로 창업 진출입시 세심한 주의가 필요한 상권(지역), 
    특정시점 사업체의 영업기간이 서울시 평균 생존영업기간보다 낮고, 서울시 평균 폐업영업기간보다 낮은 상권(지역)
- LH(상권확장) : 
    경쟁력 있는 신규 창업 우위 상권(지역), 
    특정 시점 사업체의 영업기간이 서울시 평균 생존영업기간보다 낮고, 서울시 평균 폐업영업기간보다 높은 상권(지역)
- HL(상권축소) : 
    경쟁력 있는 기존 업체 우위 상권(지역), 
    특정 시점 사업체의 영업기간이 서울시 평균 생존영업기간보다 높고, 서울시 평균 폐업영업기간보다 낮은 상권(지역)
- HH(정체) : 
    창업 진출입시 세심한 주의 상권(지역), 
    특정 시점 사업체의 영업기간이 서울시 평균 생존영업기간보다 높고, 서울시 평균 폐업영업기간보다 높은 상권(지역)
다이나믹(LL) = 3
상권확장(LH) = 2
정체(HH) = 1
상권축소(HL) = 0
'''
dong_change.loc[dong_change['상권_변화_지표'] == 'LL', '상권_변화_지표'] = 3
dong_change.loc[dong_change['상권_변화_지표'] == 'LH', '상권_변화_지표'] = 2
dong_change.loc[dong_change['상권_변화_지표'] == 'HH', '상권_변화_지표'] = 1
dong_change.loc[dong_change['상권_변화_지표'] == 'HL', '상권_변화_지표'] = 0
dong_change['상권_변화_지표'] = np.array(dong_change['상권_변화_지표'], dtype='int64')

In [7]:
'''
상권변화와 운영영개월 평균은 반비례 
즉 축소시기일때 영업개월 평균이 늘어나고 폐업 영업개월평균이 
'''
dong_change[['상권_변화_지표','운영_영업_개월_평균','폐업_영업_개월_평균']].corr()

             상권_변화_지표  운영_영업_개월_평균  폐업_영업_개월_평균
상권_변화_지표     1.000000    -0.614317    -0.378575
운영_영업_개월_평균 -0.614317     1.000000     0.659696
폐업_영업_개월_평균 -0.378575     0.659696     1.000000

In [46]:
dong_change = dong_change.drop('상권_변화_지표_명', axis=1)

In [9]:
dong_change

,기준_년_코드,기준_분기_코드,행정동_코드,행정동_코드_명,상권_변화_지표,상권_변화_지표_명,운영_영업_개월_평균,폐업_영업_개월_평균,서울_운영_영업_개월_평균,서울_폐업_영업_개월_평균
848,2021,4,11740700,둔촌2동,0,상권축소,120,52,118,55
849,2021,4,11740690,둔촌1동,1,정체,172,72,118,55
850,2021,4,11740685,길동,3,다이나믹,111,49,118,55
851,2021,4,11740660,성내3동,0,상권축소,120,49,118,55
852,2021,4,11740650,성내2동,3,다이나믹,117,49,118,55
...,...,...,...,...,...,...,...,...,...,...
2539,2021,1,11110560,평창동,1,정체,122,60,115,54
2540,2021,1,11110550,부암동,2,상권확장,103,59,115,54
2541,2021,1,11110540,삼청동,2,상권확장,103,57,115,54
2542,2021,1,11110530,사직동,1,정체,129,61,115,54
2543,2021,1,11110515,청운효자동,2,상권확장,105,61,115,54