### 생활후보지 정보
 - 아파트 비율, 거주인구 비율, 직장인구 비율, 1인가구 비율, 65세 이상 인구 비율, 20대 인구 비율

In [2]:
import requests, bs4
import pandas as pd
from lxml import html
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus, unquote
from bs4 import BeautifulSoup
import json
import xmltodict
import re
import pickle

In [5]:
# 엑세스 토큰발급
url = 'https://sgisapi.kostat.go.kr/OpenAPI3/auth/authentication.json'
params = {
        "consumer_key": "367e41f572b2440d8023",
        "consumer_secret": "d63aed3ea67741e5a424",
}

response = requests.get(url, params=params)
res = response.json()
token = res['result']['accessToken']
token

'94a10ebe-c6f7-4659-8991-781e126e65ea'

In [3]:
# pkl 파일 로드
with open('/Users/ran/Desktop/Code/python/jupyter/data_analysis_pj_restaurant/data_analysis/commercial_area_data/temp(dong).pkl', 'rb') as f:
    dong = pickle.load(f)

In [6]:
# 아파트 비율, 거주인구비율, 직장인구 비율, 1인가구 비율, 65세이상인구 비율, 20대인구 비율
col_list = []
row_list = []
for i in range(0, len(dong)):
    url = "https://sgisapi.kostat.go.kr/OpenAPI3/startupbiz/regiontotal.json"

    params = {
        "accessToken": "{}".format(token),
        "adm_cd": "{}".format(dong['addr_code'][i])  
    }

    response = requests.get(url, params=params)
    json = response.json()
    if i == 0:
        col_list = list(json['result'][1].keys())
    row_list.append(json['result'][1].values())
df = pd.DataFrame(row_list, columns=col_list)

In [7]:
'''
adm_cd 행정구역 코드
adm_nm 행정구역 이름
apart_per 아파트 비율
resid_ppltn_per 거주인구 비율
job_ppltn_per 직장인구 비율
one_person_family_per 1인가구 비율
sixty_five_more_ppltn_per 65세이상인구 비율
twenty_ppltn_per 20대인구 비율
'''
df

,twenty_ppltn_per,one_person_family_per,adm_cd,adm_nm,resid_ppltn_per,sixty_five_more_ppltn_per,apart_per,job_ppltn_per
0,2,4,1123068,개포1동,8,7,9,2
1,3,2,1123080,개포2동,8,4,9,2
2,4,5,1123071,개포4동,5,4,4,5
3,5,7,1123052,논현1동,3,4,3,7
4,5,6,1123053,논현2동,2,5,4,8
...,...,...,...,...,...,...,...,...
404,3,5,1102068,중림동,5,5,7,5
405,5,5,1102072,청구동,5,5,7,5
406,6,7,1102057,필동,1,5,3,9
407,5,6,1102067,황학동,5,5,5,5
408,3,6,1102054,회현동,1,8,6,9

In [8]:
# pKl 파일 저장
with open('dong_popInfo.pkl', 'wb') as f:
    pickle.dump(df, f, protocol=pickle.HIGHEST_PROTOCOL)